config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    collection do
      get 'unpublished'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :title, :body, :message => "is a required field"
	validates_uniqueness_of :body

  # Returns published articles excluding scheduled ones
  scope :published, -> { where('published = ? AND published_at <= ?', true, Time.now.utc) }

  # Find all drafts and scheduled posts
  scope :unpublished, -> { where('published = ? OR published_at > ?', false, Time.now.utc) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.published.order(published_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/unpublished
  # GET /articles/unpublished.json
  def unpublished
    @articles = Article.unpublished.order(published_at: :desc)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @articles }
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :published, :published_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def publication_status(article)
		publication_time = article.published_at.to_s(:long_ordinal)

		if article.published
			if article.published_at <= Time.now
				"Published on #{publication_time}"
			else
				"Scheduled for #{publication_time}"
			end
		else
			"This article is still a draft"
		end
	end
end

app/views/articles/_article.html.erb
<p id="notice" style="color: green"><%= notice %></p>
      <div class="article clear">
          <h2><%= link_to h(article.title), article %></h2>
          <div  class="column span-6">      
              <div class="entry">
                  <%= simple_format(article.body) %>        
              </div>
          </div>

          <div  class="column span-4 last">  
              <div class="meta">            
                  <h3>About this article</h3>
                  <%= publication_status(article) %>
              </div>

              <div class="tools">            
                  <h3>Tools</h3>
                  <%= link_to 'Edit', edit_article_path(article) %> &middot;
                  <%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
              </div>
          </div>
      </div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= field_set_tag do %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.label :published_at %><br>
      <%= f.datetime_select :published_at %>
    </div>
    <div class="field">
      <%= f.label :published %><br>
      <%= f.check_box :published %>
    </div>
  <% end %>
  <%= field_set_tag do %>
    <%= f.submit :class => "button" %>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render :partial => @articles %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render :partial => @article %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>The Rails Noob</title>
</head>
<body>
	<div id="header" class="container">
	    <div id="logo">
	      <%= link_to image_tag('logo.png', :width => '350', :alt => "The Rails Noob"), root_path %>
	    </div>

	    <ul id="nav" class="clear">
	      <li><%= link_to 'Home', root_path %></li>
	      <li><%= link_to 'Unpublished Articles', unpublished_articles_path %></li>
	      <li><%= link_to 'New Article', new_article_path %></li>
	    </ul>
	</div>

	<div id="main" class="container">
		<%= yield %>
	</div>

	<div id="footer" class="container clear">
	    <div class="column span-6">
	      &nbsp;
	    </div>

	    <div class="column span-4 last">
	      <p>
	           Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
	           Nullam sed lectus ut nisi hendrerit congue. 
	      </p>
	    </div>
	</div>
</body>
</html>